name: CI

on: [push] 

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Code
        working-directory: ${{github.workspace}}/MA3  # YOU NEED TO CHANGE THE FOLDER NAME TO YOUR OWN FOLDER NAME
        shell: bash
        run: (mkdir build;cmake -S .;cmake --build .) # NO NEED TO CHANGE HERE
    
