name: CI

on:
  push:
    branches: [ main| PA1 ]

  workflow_dispatch:

  jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Code
        working-directory: ${{github.workspace}}  # YOU NEED TO CHANGE THE FOLDER NAME TO YOUR OWN FOLDER NAME
        shell: bash
        run: (mkdir build;cmake -B build -S .;cmake --build build) # NO NEED TO CHANGE HERE
    
